# Site settings
title: CMU UPC
tagline: "This organization provides a positive learning environment for both enthusiasts and beginners alike to discuss and apply the strategies of all forms of poker, primarily Texas Hold'em. quote at a time"
url: "cmu-upc.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Contact
facebook: /cmupokerclub 
email: "cmupokerclub@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

collections:
- events

collections:
  events:
    output: true

