# Site settings
title: CMU UPC
icon: "img/logo.png"
tagline: "This organization provides a positive learning environment for both enthusiasts and beginners alike to discuss and apply the strategies of all forms of poker, primarily Texas Hold'em. quote at a time"
url: "cmu-upc.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Contact
facebook: /cmupokerclub 
email: "cmupokerclub@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

officers:
  bowen:
    name: 'Bowen Wang'
    photo: 'img/officers/bowen.png'
    position: 'President'
  brandon:
    name: 'Brandon Takao'
    photo: 'img/officers/brandon.png'
    position: 'President'
  sean:
    name: 'Sean Park'
    photo: 'img/officers/sean.jpg'
    position: 'VP of Finance / Web Developer'
  joonha:
    name: 'Joonha Lee'
    photo: 'img/officers/joonha.png'
    position: 'VP of Communications'
  bill:
    name: 'Bill Kim'
    photo: 'img/officers/bill.png'
    position: 'VP of Logistics'
  tommy:
    name: 'Tommy San Miguel'
    photo: 'img/officers/tommy.png'
    position: 'Webmaster'
  emily:
    name: 'Emily Chen'
    photo: 'img/officers/emily.png'
    position: 'Design Chair'
  bradley:
    name: 'Bradley Guan'
    photo: 'img/officers/bradley.png'
    position: 'Treasurer'

collections:
- events

collections:
  events:
    output: true
