# Site settings
title: CMU Poker Club
icon: "img/logo.png"
tagline: "The Undergraduate Poker Club provides an environment for Carnegie Mellon students to develop and apply analytical skills and strategies to the game of poker."
url: "cmu-upc.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's

force-https: True

# Contact
facebook: /cmupokerclub 
email: "cmupokerclub@gmail.com" # This is my real email address. Please don't email me.

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]

officers:
  bowen:
    name: 'Ryan Chen'
    photo: '{{site.baseurl}}/img/officers/ryan.png'
    position: 'President'
  

collections:
- events

collections:
  events:
    output: true
